# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ccdcontroller.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ccdcontroller(object):
    def setupUi(self, ccdcontroller):
        ccdcontroller.setObjectName(_fromUtf8("ccdcontroller"))
        ccdcontroller.resize(633, 437)
        self.centralWidget = QtGui.QWidget(ccdcontroller)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.layoutWidget = QtGui.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 598, 373))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.mainGrid = QtGui.QGridLayout(self.layoutWidget)
        self.mainGrid.setMargin(11)
        self.mainGrid.setSpacing(6)
        self.mainGrid.setObjectName(_fromUtf8("mainGrid"))
        self.statusLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.statusLineEdit.setReadOnly(True)
        self.statusLineEdit.setObjectName(_fromUtf8("statusLineEdit"))
        self.mainGrid.addWidget(self.statusLineEdit, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.exposurePage = QtGui.QWidget()
        self.exposurePage.setObjectName(_fromUtf8("exposurePage"))
        self.gridLayout = QtGui.QGridLayout(self.exposurePage)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.imnumSpinBox = QtGui.QSpinBox(self.exposurePage)
        self.imnumSpinBox.setObjectName(_fromUtf8("imnumSpinBox"))
        self.gridLayout.addWidget(self.imnumSpinBox, 5, 1, 1, 1)
        self.exptypeComboBox = QtGui.QComboBox(self.exposurePage)
        self.exptypeComboBox.setObjectName(_fromUtf8("exptypeComboBox"))
        self.exptypeComboBox.addItem(_fromUtf8(""))
        self.exptypeComboBox.addItem(_fromUtf8(""))
        self.exptypeComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.exptypeComboBox, 1, 1, 1, 1)
        self.imfilenameLabel = QtGui.QLabel(self.exposurePage)
        self.imfilenameLabel.setObjectName(_fromUtf8("imfilenameLabel"))
        self.gridLayout.addWidget(self.imfilenameLabel, 6, 1, 1, 1)
        self.exposeButton = QtGui.QPushButton(self.exposurePage)
        self.exposeButton.setEnabled(False)
        self.exposeButton.setObjectName(_fromUtf8("exposeButton"))
        self.gridLayout.addWidget(self.exposeButton, 1, 0, 1, 1)
        self.autoincCheckBox = QtGui.QCheckBox(self.exposurePage)
        self.autoincCheckBox.setChecked(True)
        self.autoincCheckBox.setObjectName(_fromUtf8("autoincCheckBox"))
        self.gridLayout.addWidget(self.autoincCheckBox, 5, 2, 1, 1)
        self.directoryPushButton = QtGui.QPushButton(self.exposurePage)
        self.directoryPushButton.setObjectName(_fromUtf8("directoryPushButton"))
        self.gridLayout.addWidget(self.directoryPushButton, 2, 0, 1, 1)
        self.exptimeDoubleSpinBox = QtGui.QDoubleSpinBox(self.exposurePage)
        self.exptimeDoubleSpinBox.setSingleStep(0.5)
        self.exptimeDoubleSpinBox.setObjectName(_fromUtf8("exptimeDoubleSpinBox"))
        self.gridLayout.addWidget(self.exptimeDoubleSpinBox, 1, 3, 1, 1)
        self.imnumLabel = QtGui.QLabel(self.exposurePage)
        self.imnumLabel.setObjectName(_fromUtf8("imnumLabel"))
        self.gridLayout.addWidget(self.imnumLabel, 4, 1, 1, 1)
        self.imtitleLabel = QtGui.QLabel(self.exposurePage)
        self.imtitleLabel.setObjectName(_fromUtf8("imtitleLabel"))
        self.gridLayout.addWidget(self.imtitleLabel, 2, 1, 1, 1)
        self.testimCheckBox = QtGui.QCheckBox(self.exposurePage)
        self.testimCheckBox.setObjectName(_fromUtf8("testimCheckBox"))
        self.gridLayout.addWidget(self.testimCheckBox, 1, 2, 1, 1)
        self.imtypeLabel = QtGui.QLabel(self.exposurePage)
        self.imtypeLabel.setObjectName(_fromUtf8("imtypeLabel"))
        self.gridLayout.addWidget(self.imtypeLabel, 0, 1, 1, 1)
        self.exptimeLabel = QtGui.QLabel(self.exposurePage)
        self.exptimeLabel.setObjectName(_fromUtf8("exptimeLabel"))
        self.gridLayout.addWidget(self.exptimeLabel, 0, 3, 1, 1)
        self.imtitleLineEdit = QtGui.QLineEdit(self.exposurePage)
        self.imtitleLineEdit.setObjectName(_fromUtf8("imtitleLineEdit"))
        self.gridLayout.addWidget(self.imtitleLineEdit, 3, 1, 1, 3)
        self.imfilenameLineEdit = QtGui.QLineEdit(self.exposurePage)
        self.imfilenameLineEdit.setReadOnly(True)
        self.imfilenameLineEdit.setObjectName(_fromUtf8("imfilenameLineEdit"))
        self.gridLayout.addWidget(self.imfilenameLineEdit, 7, 1, 1, 3)
        self.resetButton = QtGui.QPushButton(self.exposurePage)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.gridLayout.addWidget(self.resetButton, 7, 0, 1, 1)
        self.tabWidget.addTab(self.exposurePage, _fromUtf8(""))
        self.scanPage = QtGui.QWidget()
        self.scanPage.setObjectName(_fromUtf8("scanPage"))
        self.tabWidget.addTab(self.scanPage, _fromUtf8(""))
        self.voltagePage = QtGui.QWidget()
        self.voltagePage.setObjectName(_fromUtf8("voltagePage"))
        self.gridLayout_2 = QtGui.QGridLayout(self.voltagePage)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.vddLabel = QtGui.QLabel(self.voltagePage)
        self.vddLabel.setObjectName(_fromUtf8("vddLabel"))
        self.gridLayout_2.addWidget(self.vddLabel, 0, 0, 1, 1)
        self.vodLabel = QtGui.QLabel(self.voltagePage)
        self.vodLabel.setObjectName(_fromUtf8("vodLabel"))
        self.gridLayout_2.addWidget(self.vodLabel, 0, 1, 1, 1)
        self.vogLabel = QtGui.QLabel(self.voltagePage)
        self.vogLabel.setObjectName(_fromUtf8("vogLabel"))
        self.gridLayout_2.addWidget(self.vogLabel, 0, 2, 1, 1)
        self.vrdLabel = QtGui.QLabel(self.voltagePage)
        self.vrdLabel.setObjectName(_fromUtf8("vrdLabel"))
        self.gridLayout_2.addWidget(self.vrdLabel, 0, 3, 1, 1)
        self.vddLineEdit = QtGui.QLineEdit(self.voltagePage)
        self.vddLineEdit.setReadOnly(True)
        self.vddLineEdit.setObjectName(_fromUtf8("vddLineEdit"))
        self.gridLayout_2.addWidget(self.vddLineEdit, 1, 0, 1, 1)
        self.vodLineEdit = QtGui.QLineEdit(self.voltagePage)
        self.vodLineEdit.setReadOnly(True)
        self.vodLineEdit.setObjectName(_fromUtf8("vodLineEdit"))
        self.gridLayout_2.addWidget(self.vodLineEdit, 1, 1, 1, 1)
        self.vogLineEdit = QtGui.QLineEdit(self.voltagePage)
        self.vogLineEdit.setReadOnly(True)
        self.vogLineEdit.setObjectName(_fromUtf8("vogLineEdit"))
        self.gridLayout_2.addWidget(self.vogLineEdit, 1, 2, 1, 1)
        self.vrdLineEdit = QtGui.QLineEdit(self.voltagePage)
        self.vrdLineEdit.setReadOnly(True)
        self.vrdLineEdit.setObjectName(_fromUtf8("vrdLineEdit"))
        self.gridLayout_2.addWidget(self.vrdLineEdit, 1, 3, 1, 1)
        self.setvddLabel = QtGui.QLabel(self.voltagePage)
        self.setvddLabel.setObjectName(_fromUtf8("setvddLabel"))
        self.gridLayout_2.addWidget(self.setvddLabel, 2, 0, 1, 1)
        self.setvodLabel = QtGui.QLabel(self.voltagePage)
        self.setvodLabel.setObjectName(_fromUtf8("setvodLabel"))
        self.gridLayout_2.addWidget(self.setvodLabel, 2, 1, 1, 1)
        self.setvogLabel = QtGui.QLabel(self.voltagePage)
        self.setvogLabel.setObjectName(_fromUtf8("setvogLabel"))
        self.gridLayout_2.addWidget(self.setvogLabel, 2, 2, 1, 1)
        self.setvrdLabel = QtGui.QLabel(self.voltagePage)
        self.setvrdLabel.setObjectName(_fromUtf8("setvrdLabel"))
        self.gridLayout_2.addWidget(self.setvrdLabel, 2, 3, 1, 1)
        self.vddSpinBox = QtGui.QDoubleSpinBox(self.voltagePage)
        self.vddSpinBox.setDecimals(1)
        self.vddSpinBox.setSingleStep(0.5)
        self.vddSpinBox.setObjectName(_fromUtf8("vddSpinBox"))
        self.gridLayout_2.addWidget(self.vddSpinBox, 3, 0, 1, 1)
        self.vodSpinBox = QtGui.QDoubleSpinBox(self.voltagePage)
        self.vodSpinBox.setDecimals(1)
        self.vodSpinBox.setSingleStep(0.5)
        self.vodSpinBox.setObjectName(_fromUtf8("vodSpinBox"))
        self.gridLayout_2.addWidget(self.vodSpinBox, 3, 1, 1, 1)
        self.vogSpinBox = QtGui.QDoubleSpinBox(self.voltagePage)
        self.vogSpinBox.setDecimals(1)
        self.vogSpinBox.setSingleStep(0.5)
        self.vogSpinBox.setObjectName(_fromUtf8("vogSpinBox"))
        self.gridLayout_2.addWidget(self.vogSpinBox, 3, 2, 1, 1)
        self.vrdSpinBox = QtGui.QDoubleSpinBox(self.voltagePage)
        self.vrdSpinBox.setDecimals(1)
        self.vrdSpinBox.setSingleStep(0.5)
        self.vrdSpinBox.setProperty("value", 0.0)
        self.vrdSpinBox.setObjectName(_fromUtf8("vrdSpinBox"))
        self.gridLayout_2.addWidget(self.vrdSpinBox, 3, 3, 1, 1)
        self.resetvoltageButton = QtGui.QPushButton(self.voltagePage)
        self.resetvoltageButton.setObjectName(_fromUtf8("resetvoltageButton"))
        self.gridLayout_2.addWidget(self.resetvoltageButton, 4, 2, 1, 1)
        self.setvoltageButton = QtGui.QPushButton(self.voltagePage)
        self.setvoltageButton.setObjectName(_fromUtf8("setvoltageButton"))
        self.gridLayout_2.addWidget(self.setvoltageButton, 4, 3, 1, 1)
        self.tabWidget.addTab(self.voltagePage, _fromUtf8(""))
        self.mainGrid.addWidget(self.tabWidget, 0, 0, 1, 3)
        self.statusLabel = QtGui.QLabel(self.layoutWidget)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.mainGrid.addWidget(self.statusLabel, 1, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.mainGrid.addWidget(self.progressBar, 2, 1, 1, 1)
        ccdcontroller.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(ccdcontroller)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 633, 22))
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        ccdcontroller.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(ccdcontroller)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        ccdcontroller.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(ccdcontroller)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        ccdcontroller.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(ccdcontroller)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menu_File.addAction(self.actionExit)
        self.menuBar.addAction(self.menu_File.menuAction())

        self.retranslateUi(ccdcontroller)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ccdcontroller)

    def retranslateUi(self, ccdcontroller):
        ccdcontroller.setWindowTitle(_translate("ccdcontroller", "ccdcontroller", None))
        self.exptypeComboBox.setItemText(0, _translate("ccdcontroller", "Exposure", None))
        self.exptypeComboBox.setItemText(1, _translate("ccdcontroller", "Dark", None))
        self.exptypeComboBox.setItemText(2, _translate("ccdcontroller", "Bias", None))
        self.imfilenameLabel.setText(_translate("ccdcontroller", "Image Filename:", None))
        self.exposeButton.setText(_translate("ccdcontroller", "Expose", None))
        self.autoincCheckBox.setText(_translate("ccdcontroller", "Auto Increment?", None))
        self.directoryPushButton.setText(_translate("ccdcontroller", "Set Data Directory", None))
        self.imnumLabel.setText(_translate("ccdcontroller", "Image Number:", None))
        self.imtitleLabel.setText(_translate("ccdcontroller", "Image Title:", None))
        self.testimCheckBox.setText(_translate("ccdcontroller", "Test Image", None))
        self.imtypeLabel.setText(_translate("ccdcontroller", "Image Type:", None))
        self.exptimeLabel.setText(_translate("ccdcontroller", "Exposure Time:", None))
        self.resetButton.setText(_translate("ccdcontroller", "Reset Controller", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.exposurePage), _translate("ccdcontroller", "Exposure", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scanPage), _translate("ccdcontroller", "Scan", None))
        self.vddLabel.setText(_translate("ccdcontroller", "VDD", None))
        self.vodLabel.setText(_translate("ccdcontroller", "VOD", None))
        self.vogLabel.setText(_translate("ccdcontroller", "VOG", None))
        self.vrdLabel.setText(_translate("ccdcontroller", "VRD", None))
        self.setvddLabel.setText(_translate("ccdcontroller", "Set VDD", None))
        self.setvodLabel.setText(_translate("ccdcontroller", "Set VOD", None))
        self.setvogLabel.setText(_translate("ccdcontroller", "Set VOG", None))
        self.setvrdLabel.setText(_translate("ccdcontroller", "Set VRD", None))
        self.resetvoltageButton.setText(_translate("ccdcontroller", "Reset To Defaults", None))
        self.setvoltageButton.setText(_translate("ccdcontroller", "Set Voltages", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.voltagePage), _translate("ccdcontroller", "Voltages", None))
        self.statusLabel.setText(_translate("ccdcontroller", "Status:", None))
        self.menu_File.setTitle(_translate("ccdcontroller", "&File", None))
        self.actionExit.setText(_translate("ccdcontroller", "Exit", None))

