# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ccdcontroller.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ccdcontroller(object):
    def setupUi(self, ccdcontroller):
        ccdcontroller.setObjectName(_fromUtf8("ccdcontroller"))
        ccdcontroller.resize(800, 640)
        self.centralWidget = QtGui.QWidget(ccdcontroller)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(21, 10, 751, 331))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.exposurePage = QtGui.QWidget()
        self.exposurePage.setObjectName(_fromUtf8("exposurePage"))
        self.layoutWidget = QtGui.QWidget(self.exposurePage)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 719, 293))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.imfilenameLabel = QtGui.QLabel(self.layoutWidget)
        self.imfilenameLabel.setObjectName(_fromUtf8("imfilenameLabel"))
        self.gridLayout.addWidget(self.imfilenameLabel, 10, 3, 1, 1)
        self.imfilenameLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.imfilenameLineEdit.setEnabled(True)
        self.imfilenameLineEdit.setReadOnly(True)
        self.imfilenameLineEdit.setObjectName(_fromUtf8("imfilenameLineEdit"))
        self.gridLayout.addWidget(self.imfilenameLineEdit, 11, 3, 2, 2)
        self.imtitleLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.imtitleLineEdit.setObjectName(_fromUtf8("imtitleLineEdit"))
        self.gridLayout.addWidget(self.imtitleLineEdit, 5, 3, 2, 2)
        self.exptypeComboBox = QtGui.QComboBox(self.layoutWidget)
        self.exptypeComboBox.setObjectName(_fromUtf8("exptypeComboBox"))
        self.exptypeComboBox.addItem(_fromUtf8(""))
        self.exptypeComboBox.addItem(_fromUtf8(""))
        self.exptypeComboBox.addItem(_fromUtf8(""))
        self.exptypeComboBox.addItem(_fromUtf8(""))
        self.exptypeComboBox.addItem(_fromUtf8(""))
        self.exptypeComboBox.addItem(_fromUtf8(""))
        self.exptypeComboBox.addItem(_fromUtf8(""))
        self.exptypeComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.exptypeComboBox, 1, 3, 2, 1)
        self.testimCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.testimCheckBox.setObjectName(_fromUtf8("testimCheckBox"))
        self.gridLayout.addWidget(self.testimCheckBox, 1, 4, 2, 1)
        self.exptimeSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.exptimeSpinBox.setEnabled(True)
        self.exptimeSpinBox.setReadOnly(False)
        self.exptimeSpinBox.setDecimals(1)
        self.exptimeSpinBox.setMaximum(100000.0)
        self.exptimeSpinBox.setSingleStep(0.5)
        self.exptimeSpinBox.setObjectName(_fromUtf8("exptimeSpinBox"))
        self.gridLayout.addWidget(self.exptimeSpinBox, 1, 6, 2, 1)
        self.exposeButton = QtGui.QPushButton(self.layoutWidget)
        self.exposeButton.setEnabled(False)
        self.exposeButton.setObjectName(_fromUtf8("exposeButton"))
        self.gridLayout.addWidget(self.exposeButton, 0, 0, 1, 1)
        self.vline_1 = QtGui.QFrame(self.layoutWidget)
        self.vline_1.setFrameShape(QtGui.QFrame.VLine)
        self.vline_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.vline_1.setObjectName(_fromUtf8("vline_1"))
        self.gridLayout.addWidget(self.vline_1, 0, 1, 13, 2)
        self.imtypeLabel = QtGui.QLabel(self.layoutWidget)
        self.imtypeLabel.setObjectName(_fromUtf8("imtypeLabel"))
        self.gridLayout.addWidget(self.imtypeLabel, 0, 3, 1, 1)
        self.vline_2 = QtGui.QFrame(self.layoutWidget)
        self.vline_2.setFrameShape(QtGui.QFrame.VLine)
        self.vline_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.vline_2.setObjectName(_fromUtf8("vline_2"))
        self.gridLayout.addWidget(self.vline_2, 0, 5, 13, 1)
        self.exptimeLabel = QtGui.QLabel(self.layoutWidget)
        self.exptimeLabel.setObjectName(_fromUtf8("exptimeLabel"))
        self.gridLayout.addWidget(self.exptimeLabel, 0, 6, 1, 1)
        self.directoryPushButton = QtGui.QPushButton(self.layoutWidget)
        self.directoryPushButton.setObjectName(_fromUtf8("directoryPushButton"))
        self.gridLayout.addWidget(self.directoryPushButton, 1, 0, 2, 1)
        self.hline_1 = QtGui.QFrame(self.layoutWidget)
        self.hline_1.setFrameShape(QtGui.QFrame.HLine)
        self.hline_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.hline_1.setObjectName(_fromUtf8("hline_1"))
        self.gridLayout.addWidget(self.hline_1, 3, 6, 1, 2)
        self.imtitleLabel = QtGui.QLabel(self.layoutWidget)
        self.imtitleLabel.setObjectName(_fromUtf8("imtitleLabel"))
        self.gridLayout.addWidget(self.imtitleLabel, 4, 3, 1, 1)
        self.minexpLabel = QtGui.QLabel(self.layoutWidget)
        self.minexpLabel.setObjectName(_fromUtf8("minexpLabel"))
        self.gridLayout.addWidget(self.minexpLabel, 4, 6, 1, 1)
        self.maxexpLabel = QtGui.QLabel(self.layoutWidget)
        self.maxexpLabel.setObjectName(_fromUtf8("maxexpLabel"))
        self.gridLayout.addWidget(self.maxexpLabel, 4, 7, 1, 1)
        self.minexpSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.minexpSpinBox.setDecimals(1)
        self.minexpSpinBox.setObjectName(_fromUtf8("minexpSpinBox"))
        self.gridLayout.addWidget(self.minexpSpinBox, 5, 6, 2, 1)
        self.maxexpSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.maxexpSpinBox.setDecimals(1)
        self.maxexpSpinBox.setObjectName(_fromUtf8("maxexpSpinBox"))
        self.gridLayout.addWidget(self.maxexpSpinBox, 5, 7, 2, 1)
        self.filterComboBox = QtGui.QComboBox(self.layoutWidget)
        self.filterComboBox.setObjectName(_fromUtf8("filterComboBox"))
        self.filterComboBox.addItem(_fromUtf8(""))
        self.filterComboBox.addItem(_fromUtf8(""))
        self.filterComboBox.addItem(_fromUtf8(""))
        self.filterComboBox.addItem(_fromUtf8(""))
        self.filterComboBox.addItem(_fromUtf8(""))
        self.filterComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.filterComboBox, 5, 0, 2, 1)
        self.imnumLabel = QtGui.QLabel(self.layoutWidget)
        self.imnumLabel.setObjectName(_fromUtf8("imnumLabel"))
        self.gridLayout.addWidget(self.imnumLabel, 7, 3, 1, 1)
        self.tstepLabel = QtGui.QLabel(self.layoutWidget)
        self.tstepLabel.setObjectName(_fromUtf8("tstepLabel"))
        self.gridLayout.addWidget(self.tstepLabel, 7, 6, 1, 1)
        self.imnumSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.imnumSpinBox.setMinimum(1)
        self.imnumSpinBox.setMaximum(999)
        self.imnumSpinBox.setObjectName(_fromUtf8("imnumSpinBox"))
        self.gridLayout.addWidget(self.imnumSpinBox, 8, 3, 1, 1)
        self.autoincCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.autoincCheckBox.setChecked(True)
        self.autoincCheckBox.setObjectName(_fromUtf8("autoincCheckBox"))
        self.gridLayout.addWidget(self.autoincCheckBox, 8, 4, 1, 1)
        self.tstepSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.tstepSpinBox.setDecimals(1)
        self.tstepSpinBox.setObjectName(_fromUtf8("tstepSpinBox"))
        self.gridLayout.addWidget(self.tstepSpinBox, 8, 6, 1, 1)
        self.hline_2 = QtGui.QFrame(self.layoutWidget)
        self.hline_2.setFrameShape(QtGui.QFrame.HLine)
        self.hline_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.hline_2.setObjectName(_fromUtf8("hline_2"))
        self.gridLayout.addWidget(self.hline_2, 9, 6, 1, 2)
        self.imstackLabel = QtGui.QLabel(self.layoutWidget)
        self.imstackLabel.setObjectName(_fromUtf8("imstackLabel"))
        self.gridLayout.addWidget(self.imstackLabel, 10, 6, 1, 1)
        self.imstackSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.imstackSpinBox.setMinimum(1)
        self.imstackSpinBox.setMaximum(999)
        self.imstackSpinBox.setObjectName(_fromUtf8("imstackSpinBox"))
        self.gridLayout.addWidget(self.imstackSpinBox, 11, 6, 2, 1)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 3, 0, 1, 1)
        self.filterToggleButton = QtGui.QPushButton(self.layoutWidget)
        self.filterToggleButton.setCheckable(True)
        self.filterToggleButton.setChecked(True)
        self.filterToggleButton.setObjectName(_fromUtf8("filterToggleButton"))
        self.gridLayout.addWidget(self.filterToggleButton, 4, 0, 1, 1)
        self.monoSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.monoSpinBox.setEnabled(False)
        self.monoSpinBox.setMinimum(300)
        self.monoSpinBox.setMaximum(1000)
        self.monoSpinBox.setSingleStep(5)
        self.monoSpinBox.setObjectName(_fromUtf8("monoSpinBox"))
        self.gridLayout.addWidget(self.monoSpinBox, 7, 0, 1, 1)
        self.tabWidget.addTab(self.exposurePage, _fromUtf8(""))
        self.voltagePage = QtGui.QWidget()
        self.voltagePage.setObjectName(_fromUtf8("voltagePage"))
        self.layoutWidget1 = QtGui.QWidget(self.voltagePage)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 721, 271))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.vrdLabel = QtGui.QLabel(self.layoutWidget1)
        self.vrdLabel.setObjectName(_fromUtf8("vrdLabel"))
        self.gridLayout_2.addWidget(self.vrdLabel, 0, 3, 1, 1)
        self.parhiLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.parhiLineEdit.setReadOnly(True)
        self.parhiLineEdit.setObjectName(_fromUtf8("parhiLineEdit"))
        self.gridLayout_2.addWidget(self.parhiLineEdit, 3, 0, 1, 1)
        self.vddLabel = QtGui.QLabel(self.layoutWidget1)
        self.vddLabel.setObjectName(_fromUtf8("vddLabel"))
        self.gridLayout_2.addWidget(self.vddLabel, 0, 0, 1, 1)
        self.vodLabel = QtGui.QLabel(self.layoutWidget1)
        self.vodLabel.setObjectName(_fromUtf8("vodLabel"))
        self.gridLayout_2.addWidget(self.vodLabel, 0, 1, 1, 1)
        self.vogLabel = QtGui.QLabel(self.layoutWidget1)
        self.vogLabel.setObjectName(_fromUtf8("vogLabel"))
        self.gridLayout_2.addWidget(self.vogLabel, 0, 2, 1, 1)
        self.rghiLabel = QtGui.QLabel(self.layoutWidget1)
        self.rghiLabel.setObjectName(_fromUtf8("rghiLabel"))
        self.gridLayout_2.addWidget(self.rghiLabel, 0, 4, 1, 1)
        self.vodLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.vodLineEdit.setReadOnly(True)
        self.vodLineEdit.setObjectName(_fromUtf8("vodLineEdit"))
        self.gridLayout_2.addWidget(self.vodLineEdit, 1, 1, 1, 1)
        self.vddLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.vddLineEdit.setReadOnly(True)
        self.vddLineEdit.setObjectName(_fromUtf8("vddLineEdit"))
        self.gridLayout_2.addWidget(self.vddLineEdit, 1, 0, 1, 1)
        self.rgloLabel = QtGui.QLabel(self.layoutWidget1)
        self.rgloLabel.setObjectName(_fromUtf8("rgloLabel"))
        self.gridLayout_2.addWidget(self.rgloLabel, 0, 5, 1, 1)
        self.vogLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.vogLineEdit.setReadOnly(True)
        self.vogLineEdit.setObjectName(_fromUtf8("vogLineEdit"))
        self.gridLayout_2.addWidget(self.vogLineEdit, 1, 2, 1, 1)
        self.vrdLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.vrdLineEdit.setReadOnly(True)
        self.vrdLineEdit.setObjectName(_fromUtf8("vrdLineEdit"))
        self.gridLayout_2.addWidget(self.vrdLineEdit, 1, 3, 1, 1)
        self.setvoltageButton = QtGui.QPushButton(self.layoutWidget1)
        self.setvoltageButton.setObjectName(_fromUtf8("setvoltageButton"))
        self.gridLayout_2.addWidget(self.setvoltageButton, 6, 4, 1, 2)
        self.rghiLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.rghiLineEdit.setReadOnly(True)
        self.rghiLineEdit.setObjectName(_fromUtf8("rghiLineEdit"))
        self.gridLayout_2.addWidget(self.rghiLineEdit, 1, 4, 1, 1)
        self.rgloLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.rgloLineEdit.setReadOnly(True)
        self.rgloLineEdit.setObjectName(_fromUtf8("rgloLineEdit"))
        self.gridLayout_2.addWidget(self.rgloLineEdit, 1, 5, 1, 1)
        self.parhiLabel = QtGui.QLabel(self.layoutWidget1)
        self.parhiLabel.setObjectName(_fromUtf8("parhiLabel"))
        self.gridLayout_2.addWidget(self.parhiLabel, 2, 0, 1, 1)
        self.parloLabel = QtGui.QLabel(self.layoutWidget1)
        self.parloLabel.setObjectName(_fromUtf8("parloLabel"))
        self.gridLayout_2.addWidget(self.parloLabel, 2, 1, 1, 1)
        self.serhiLabel = QtGui.QLabel(self.layoutWidget1)
        self.serhiLabel.setObjectName(_fromUtf8("serhiLabel"))
        self.gridLayout_2.addWidget(self.serhiLabel, 2, 2, 1, 1)
        self.serloLabel = QtGui.QLabel(self.layoutWidget1)
        self.serloLabel.setObjectName(_fromUtf8("serloLabel"))
        self.gridLayout_2.addWidget(self.serloLabel, 2, 3, 1, 1)
        self.parloLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.parloLineEdit.setReadOnly(True)
        self.parloLineEdit.setObjectName(_fromUtf8("parloLineEdit"))
        self.gridLayout_2.addWidget(self.parloLineEdit, 3, 1, 1, 1)
        self.serloLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.serloLineEdit.setReadOnly(True)
        self.serloLineEdit.setObjectName(_fromUtf8("serloLineEdit"))
        self.gridLayout_2.addWidget(self.serloLineEdit, 3, 3, 1, 1)
        self.serhiLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.serhiLineEdit.setReadOnly(True)
        self.serhiLineEdit.setObjectName(_fromUtf8("serhiLineEdit"))
        self.gridLayout_2.addWidget(self.serhiLineEdit, 3, 2, 1, 1)
        self.voltageComboBox = QtGui.QComboBox(self.layoutWidget1)
        self.voltageComboBox.setObjectName(_fromUtf8("voltageComboBox"))
        self.voltageComboBox.addItem(_fromUtf8(""))
        self.voltageComboBox.addItem(_fromUtf8(""))
        self.voltageComboBox.addItem(_fromUtf8(""))
        self.voltageComboBox.addItem(_fromUtf8(""))
        self.voltageComboBox.addItem(_fromUtf8(""))
        self.voltageComboBox.addItem(_fromUtf8(""))
        self.voltageComboBox.addItem(_fromUtf8(""))
        self.voltageComboBox.addItem(_fromUtf8(""))
        self.voltageComboBox.addItem(_fromUtf8(""))
        self.voltageComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.voltageComboBox, 5, 4, 1, 1)
        self.voltageSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.voltageSpinBox.setObjectName(_fromUtf8("voltageSpinBox"))
        self.gridLayout_2.addWidget(self.voltageSpinBox, 5, 5, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 5, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 3, 1, 1)
        self.resetvoltageButton = QtGui.QPushButton(self.layoutWidget1)
        self.resetvoltageButton.setObjectName(_fromUtf8("resetvoltageButton"))
        self.gridLayout_2.addWidget(self.resetvoltageButton, 6, 0, 1, 2)
        self.tabWidget.addTab(self.voltagePage, _fromUtf8(""))
        self.layoutWidget2 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 350, 751, 221))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setMargin(11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.statusLabel = QtGui.QLabel(self.layoutWidget2)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.gridLayout_3.addWidget(self.statusLabel, 0, 0, 1, 1)
        self.statusEdit = QtGui.QTextEdit(self.layoutWidget2)
        self.statusEdit.setReadOnly(True)
        self.statusEdit.setObjectName(_fromUtf8("statusEdit"))
        self.gridLayout_3.addWidget(self.statusEdit, 0, 1, 1, 3)
        self.progressBar = QtGui.QProgressBar(self.layoutWidget2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_3.addWidget(self.progressBar, 1, 1, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(438, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.resetButton = QtGui.QPushButton(self.layoutWidget2)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.gridLayout_3.addWidget(self.resetButton, 2, 2, 1, 1)
        self.shutdownButton = QtGui.QPushButton(self.layoutWidget2)
        self.shutdownButton.setObjectName(_fromUtf8("shutdownButton"))
        self.gridLayout_3.addWidget(self.shutdownButton, 2, 3, 1, 1)
        ccdcontroller.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(ccdcontroller)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        ccdcontroller.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(ccdcontroller)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        ccdcontroller.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(ccdcontroller)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        ccdcontroller.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(ccdcontroller)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menu_File.addAction(self.actionExit)
        self.menuBar.addAction(self.menu_File.menuAction())

        self.retranslateUi(ccdcontroller)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ccdcontroller)

    def retranslateUi(self, ccdcontroller):
        ccdcontroller.setWindowTitle(_translate("ccdcontroller", "ccdcontroller", None))
        self.imfilenameLabel.setText(_translate("ccdcontroller", "Data Directory:", None))
        self.exptypeComboBox.setItemText(0, _translate("ccdcontroller", "Exposure", None))
        self.exptypeComboBox.setItemText(1, _translate("ccdcontroller", "Exposure Stack", None))
        self.exptypeComboBox.setItemText(2, _translate("ccdcontroller", "Exposure Series", None))
        self.exptypeComboBox.setItemText(3, _translate("ccdcontroller", "Dark", None))
        self.exptypeComboBox.setItemText(4, _translate("ccdcontroller", "Dark Stack", None))
        self.exptypeComboBox.setItemText(5, _translate("ccdcontroller", "Dark Series", None))
        self.exptypeComboBox.setItemText(6, _translate("ccdcontroller", "Bias", None))
        self.exptypeComboBox.setItemText(7, _translate("ccdcontroller", "Bias Stack", None))
        self.testimCheckBox.setText(_translate("ccdcontroller", "Test Image", None))
        self.exposeButton.setText(_translate("ccdcontroller", "Expose", None))
        self.imtypeLabel.setText(_translate("ccdcontroller", "Image Type:", None))
        self.exptimeLabel.setText(_translate("ccdcontroller", "Exposure Time:", None))
        self.directoryPushButton.setText(_translate("ccdcontroller", "Change Directory", None))
        self.imtitleLabel.setText(_translate("ccdcontroller", "Image Title:", None))
        self.minexpLabel.setText(_translate("ccdcontroller", "Min Exposure Time:", None))
        self.maxexpLabel.setText(_translate("ccdcontroller", "Max Exposure Time:", None))
        self.filterComboBox.setItemText(0, _translate("ccdcontroller", "u", None))
        self.filterComboBox.setItemText(1, _translate("ccdcontroller", "g", None))
        self.filterComboBox.setItemText(2, _translate("ccdcontroller", "r", None))
        self.filterComboBox.setItemText(3, _translate("ccdcontroller", "i", None))
        self.filterComboBox.setItemText(4, _translate("ccdcontroller", "z", None))
        self.filterComboBox.setItemText(5, _translate("ccdcontroller", "y", None))
        self.imnumLabel.setText(_translate("ccdcontroller", "Sequence Number:", None))
        self.tstepLabel.setText(_translate("ccdcontroller", "Time Step:", None))
        self.autoincCheckBox.setText(_translate("ccdcontroller", "Auto Increment?", None))
        self.imstackLabel.setText(_translate("ccdcontroller", "# of Exposures:", None))
        self.filterToggleButton.setText(_translate("ccdcontroller", "Filter", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.exposurePage), _translate("ccdcontroller", "Exposure", None))
        self.vrdLabel.setText(_translate("ccdcontroller", "VRD", None))
        self.parhiLineEdit.setText(_translate("ccdcontroller", "0.00", None))
        self.vddLabel.setText(_translate("ccdcontroller", "VDD", None))
        self.vodLabel.setText(_translate("ccdcontroller", "VOD", None))
        self.vogLabel.setText(_translate("ccdcontroller", "VOG", None))
        self.rghiLabel.setText(_translate("ccdcontroller", "RG HI", None))
        self.vodLineEdit.setText(_translate("ccdcontroller", "0.00", None))
        self.vddLineEdit.setText(_translate("ccdcontroller", "1.00", None))
        self.rgloLabel.setText(_translate("ccdcontroller", "RG LO", None))
        self.vogLineEdit.setText(_translate("ccdcontroller", "0.00", None))
        self.vrdLineEdit.setText(_translate("ccdcontroller", "0.00", None))
        self.setvoltageButton.setText(_translate("ccdcontroller", "Set Voltage", None))
        self.rghiLineEdit.setText(_translate("ccdcontroller", "0.00", None))
        self.rgloLineEdit.setText(_translate("ccdcontroller", "0.00", None))
        self.parhiLabel.setText(_translate("ccdcontroller", "PAR HI", None))
        self.parloLabel.setText(_translate("ccdcontroller", "PAR LO", None))
        self.serhiLabel.setText(_translate("ccdcontroller", "SER HI", None))
        self.serloLabel.setText(_translate("ccdcontroller", "SER LO", None))
        self.parloLineEdit.setText(_translate("ccdcontroller", "0.00", None))
        self.serloLineEdit.setText(_translate("ccdcontroller", "0.00", None))
        self.serhiLineEdit.setText(_translate("ccdcontroller", "0.00", None))
        self.voltageComboBox.setItemText(0, _translate("ccdcontroller", "VDD", None))
        self.voltageComboBox.setItemText(1, _translate("ccdcontroller", "VOD", None))
        self.voltageComboBox.setItemText(2, _translate("ccdcontroller", "VOG", None))
        self.voltageComboBox.setItemText(3, _translate("ccdcontroller", "VRD", None))
        self.voltageComboBox.setItemText(4, _translate("ccdcontroller", "RG HI", None))
        self.voltageComboBox.setItemText(5, _translate("ccdcontroller", "RG LO", None))
        self.voltageComboBox.setItemText(6, _translate("ccdcontroller", "PAR HI", None))
        self.voltageComboBox.setItemText(7, _translate("ccdcontroller", "PAR LO", None))
        self.voltageComboBox.setItemText(8, _translate("ccdcontroller", "SER HI", None))
        self.voltageComboBox.setItemText(9, _translate("ccdcontroller", "SER LO", None))
        self.label.setText(_translate("ccdcontroller", "Select Voltage", None))
        self.resetvoltageButton.setText(_translate("ccdcontroller", "Reset To Defaults", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.voltagePage), _translate("ccdcontroller", "Voltages", None))
        self.statusLabel.setText(_translate("ccdcontroller", "Status:", None))
        self.resetButton.setText(_translate("ccdcontroller", "Reset Controller", None))
        self.shutdownButton.setText(_translate("ccdcontroller", "Shutdown", None))
        self.menu_File.setTitle(_translate("ccdcontroller", "&File", None))
        self.actionExit.setText(_translate("ccdcontroller", "Exit", None))

